# Shared
shared_config:
  observation_dim: 33
  action_dim: 4

# Buffer Config
buffer_config:
  buffer_size: 500000
  min_buffer_size: 50000

# Actor Config
actor_config:
  layers:
    fc1: 32
    fc2: 32

# Critic Config
critic_config:
  layers:
    fc1: 32
    fc2: 32

# Agent Config
agent_config:
  action_high: 1.0
  action_low: -1.0
  batch_size: 64
  gamma: 0.99
  actor_learning_rate: 1e-5
  critic_learning_rate: 1e-5
  tau: 2e-3

# Ornstein-Uhlenbeck-Noise Config
ou_config:
  mu: 0
  theta: 0.15
  max_sigma: 0.3
  # min_sigma: 0.1
  decay_period: 100000
