# Shared values
shared_config:
  observation_dim: 37
  action_dim: 4
  seed: 1

# Buffer Config
buffer_config:
  buffer_size: 500000
  min_buffer_size: 50000
  batch_size: 64
  alpha: 0.5
  beta: 0.0
  beta_growth_period: 500000

# Network Config
network_config:
  layers:
    fc1: 32
    fc2: 32
  sigma: 0.05
  alpha: 0.999

# Agent Config
agent_config:
  epsilon: 0.2
  min_epsilon: 0.01
  epsilon_decay_period: 10000
  gamma: 0.99
  learning_rate: 10e-5
  tau: 2e-3
  prioritising: True
  noisy: True