# Shared values
observation_dim: 37
action_dim: 4
seed: 42

# Buffer Config
buffer_size: 500000
min_buffer_size: 50000

# Network Config
layers:
  fc1: 16
  fc2: 16

# Agent Config
batch_size: 64
epsilon: 1
min_epsilon: 0.1
epsilon_decay_period: 50000
gamma: 0.99
learning_rate: 10e-5
update_period: 30000
tau: 2e-3