# Shared values
shared_config:
  observation_dim: 37
  action_dim: 4
  seed: 1

# Buffer Config
buffer_config:
  buffer_size: 500000
  min_buffer_size: 50000

# Network Config
network_config:
  layers:
    fc1: 32
    fc2: 32

# Agent Config
agent_config:
  batch_size: 64
  epsilon: 1
  min_epsilon: 0.1
  epsilon_decay_period: 50000
  gamma: 0.99
  learning_rate: 10e-5
  tau: 2e-3